Link to landing page
cda-tum/mqt-qecc pull request #218
Opened 2024-04-25 08:49 UTC by lucasberent

## Description

Adds link to mqt landing page in logo and acknowledgements.

## Checklist:

- [ ] The pull request only contains commits that are related to it.
- [ ] I have added appropriate tests and documentation.
- [ ] I have made sure that all CI jobs on GitHub pass.
- [ ] The pull request introduces no new warnings and follows the project's style guidelines.

2024-04-25 09:24 UTC, burgholzer requested changes
I left a couple of small comments.

Note that you might also want to take this opportunity to add Acks to the RtD pages. You should be able to adapt that from the other projects as well.

2024-04-25 09:25 UTC, burgholzer commented
The test failures here are unrelated. They are due to GitHub moving macOS-latest to ARM runners. I'll quickly fix that up later.

2024-04-25 11:12 UTC, burgholzer commented
> The test failures here are unrelated. They are due to GitHub moving macOS-latest to ARM runners. I'll quickly fix that up later.

See https://github.com/cda-tum/mqt-qecc/pull/219

2024-04-28 19:33 UTC, lucasberent commented on README.md
> +   <a href="https://github.com/cda-tum/mqt"><img src="https://raw.githubusercontent.com/cda-tum/mqt-core/main/docs/_static/mqt_dark.png" width="60%"></a>
putting the img inside the a tag makes it a clickable link, is that not the desired functinality?

2024-04-28 19:35 UTC, lucasberent commented
> > The test failures here are unrelated. They are due to GitHub moving macOS-latest to ARM runners. I'll quickly fix that up later.
> 
> See #219

thank you sm!

2024-04-28 19:37 UTC, burgholzer commented on README.md
> +   <a href="https://github.com/cda-tum/mqt"><img src="https://raw.githubusercontent.com/cda-tum/mqt-core/main/docs/_static/mqt_dark.png" width="60%"></a>
Compare your code with the code in mqt-core ;-)
You are only wrapping one of the two images instead of both.

2024-04-28 19:47 UTC, lucasberent commented on README.md
> +   <a href="https://github.com/cda-tum/mqt"><img src="https://raw.githubusercontent.com/cda-tum/mqt-core/main/docs/_static/mqt_dark.png" width="60%"></a>
https://github.com/cda-tum/mqt-core/pull/469/files#diff-85933aa74a2d66c3e4dcdf7a9ad8397f5a7971080d34ef1108296a7c6b69e7e3

I think I am missing something, or is there no link at all on the pictures?

2024-04-28 19:51 UTC, burgholzer commented on README.md
> +   <a href="https://github.com/cda-tum/mqt"><img src="https://raw.githubusercontent.com/cda-tum/mqt-core/main/docs/_static/mqt_dark.png" width="60%"></a>
You are looking at the wrong version of the file ;o)
You want to be looking at https://github.com/cda-tum/mqt-core/blob/main/README.md (the main branch)

2024-04-29 09:49 UTC, lucasberent commented on README.md
> +   <a href="https://github.com/cda-tum/mqt"><img src="https://raw.githubusercontent.com/cda-tum/mqt-core/main/docs/_static/mqt_dark.png" width="60%"></a>
whoops, sorry :laughing: 
should be ok now

2024-04-29 09:54 UTC, burgholzer approved these changes
Lgtm 👍🏻👍🏻

2024-04-29 13:33 UTC, merged